### ISSUE TITLE
Utilize Set over Arrays for Performance

### ISSUE THREAD

**Issue by LaughDonor** [MansurAliKoroglu/enforce-unique#1]
Bigger performance boost, and handle unique entries better?

https://github.com/MansurAliKoroglu/enforce-unique/blob/af8a2a2872008a313feceb98b1bac2e53edd4279/src/unique-enforcer.ts#L19

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

> The [has](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) method checks if a value is in the set, using an approach that is, on average, quicker than testing most of the elements that have previously been added to the set. In particular, it is, on average, faster than the [Array.prototype.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) method when an array has a length equal to a set's size.

**Comment by MansurAliKoroglu** [comment]
Thank you for your feedback. Your suggestions are now published.
